"""Shared pieces for vecshift's self-contained HTML pages: the page shell, logo,
favicon, styles, script, escaping, and number formatting."""

from __future__ import annotations

import base64
import hashlib
import math
import re
from datetime import UTC, datetime
from html import escape
from importlib.resources import files
from urllib.parse import quote

# The vecshift mark: points moving from the old embedding space into the new one.
# Generated by scripts/make_logo.py; colours come from the --mark-* tokens in report.css.
DOTS = ((6.0, 25.0, 2.6), (11.2, 20.0, 3.2), (17.6, 13.8, 4.0), (25.0, 7.0, 5.0))
LOGO = (
    '<svg width="20" height="20" viewBox="0 0 32 32" aria-hidden="true">'
    + "".join(
        f'<circle cx="{x}" cy="{y}" r="{r}" fill="var(--mark-{i})"/>'
        for i, (x, y, r) in enumerate(DOTS)
    )
    + "</svg>"
)
FAVICON = "data:image/svg+xml," + quote(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><style>'
    ".a{fill:#a9a8a1}.b{fill:#839ab5}.c{fill:#5b8bc7}.d{fill:#2a78d6}"
    "@media (prefers-color-scheme:dark){.a{fill:#8a8983}.b{fill:#738ba5}"
    ".c{fill:#5a8ac5}.d{fill:#3987e5}}</style>"
    + "".join(
        f'<circle class="{c}" cx="{x}" cy="{y}" r="{r}"/>'
        for c, (x, y, r) in zip("abcd", DOTS, strict=True)
    )
    + "</svg>"
)


def e(value: object) -> str:
    """Escape for HTML text and attribute values."""
    return escape(str(value), quote=True)


def rich(text: str) -> str:
    """Escape ``text`` and show its `backticked` names as code."""
    return re.sub(r"`([^`]+)`", r"<code>\1</code>", e(text))


def compact(n: int) -> str:
    """1,284 · 12.9K · 4.2M"""
    if abs(n) < 10_000:
        return f"{n:,}"
    for size, suffix in ((1_000_000_000, "B"), (1_000_000, "M"), (1_000, "K")):
        if abs(n) >= size:
            value = n / size
            text = f"{value:.1f}".rstrip("0").rstrip(".") if value < 100 else f"{value:.0f}"
            return f"{text}{suffix}"
    return f"{n:,}"  # pragma: no cover


def percent(part: int, whole: int) -> str:
    if whole <= 0:
        return "—"
    value = 100 * part / whole
    if 0 < value < 1:
        return "<1%"
    if 99 < value < 100:
        return ">99%"
    return f"{value:.0f}%"


def nice_ceiling(n: int) -> int:
    if n <= 1:
        return 1
    magnitude = 10 ** math.floor(math.log10(n))
    for step in (1, 2, 2.5, 5, 10):
        if n <= step * magnitude:
            return int(step * magnitude) if step * magnitude >= 1 else 1
    return n  # pragma: no cover


def asset(name: str) -> str:
    return files("vecshift").joinpath("assets", name).read_text(encoding="utf-8")


def stamp(when: datetime | None = None) -> str:
    moment = (when or datetime.now(UTC)).astimezone(UTC)
    return f"{moment.day} {moment:%b %Y, %H:%M} UTC"


def content_security_policy(script: str) -> str:
    """Allow only this page's own script (by hash) and inline styles, and no network at all.

    Even if an escaping bug ever let data inject markup, the browser would refuse to run
    any other script or send anything anywhere.
    """
    digest = base64.b64encode(hashlib.sha256(script.encode()).digest()).decode()
    return (
        "default-src 'none'; img-src data:; style-src 'unsafe-inline'; "
        f"script-src 'sha256-{digest}'; base-uri 'none'; form-action 'none'"
    )


def page(
    *,
    title: str,
    product: str,
    heading: str,
    meta: list[str],
    body: str,
    footer: str,
    generator: str,
    extra_css: str = "",
) -> str:
    """A complete, self-contained HTML document in vecshift's report style."""
    meta_html = "".join(f"<span>{e(m)}</span>" for m in meta)
    script = asset("report.js")
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="{content_security_policy(script)}">
<meta name="referrer" content="no-referrer">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="{e(generator)}">
<link rel="icon" href="{FAVICON}">
<title>{e(title)}</title>
<style>{asset("report.css")}{extra_css}</style>
</head>
<body>
<main class="wrap">
<header>
<div class="brand">{LOGO}{e(product)}</div>
<h1>{e(heading)}</h1>
<p class="meta">{meta_html}</p>
</header>
{body}
<footer>{footer}</footer>
</main>
<script>{script}</script>
</body>
</html>
"""
